name: Android Worker

on:
  push:
    branches: [ '*' ]
  pull_request: 
    branches: [ '*' ]

jobs:
  unit_tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 1

      - name: set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: zulu
          java-version: 17
          cache: gradle

      - name: unit tests
        working-directory: ./
        run: ./gradlew testDebugUnitTest

      - name: verify test results
        uses: asadmansr/android-test-report-action@v1.2.0
        if: ${{ always() }}

  detekt:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 1

      - name: set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: zulu
          java-version: 17
          cache: gradle

      - name: run detekt + ktlint
        working-directory: ./
        run: ./gradlew detekt

  android-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 1

      - name: set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: zulu
          java-version: 17
          cache: gradle

      - name: run Android lint
        working-directory: ./
        run: ./gradlew lintDebug

      - uses: yutailang0119/action-android-lint@v3
        with:
          report-path: build/reports/*.xml
        continue-on-error: false

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 1

      - name: set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: zulu
          java-version: 17
          cache: gradle

      - name: building
        working-directory: ./
        run: ./gradlew assembleDebug